### PR TITLE
update lifeVM

### LINKED ISSUE #33: Updating lifeVM
Recent lifeVM update includes using 

- latest wagon
- using wagon's wasm validator

Upgrade life and wagon

### PR DESCRIPTION
**Pull request by kleash**
* Updating life to latest version
* Updating wagon to v0.6.0 and all indirect dependencies of life
* Wasm validation function changed from using lifeVM to wagon directly

Fixes #33

### CODE REVIEW

**Review by MHBauer — CHANGES_REQUESTED** [review]
Remove the chaincode binary file wasmcc/fabric-chaincode-wasmcc , unless we need it?

Looks like a very clean upgrade otherwise.

**Comment by kleash** [comment]
> Remove the chaincode binary file wasmcc/fabric-chaincode-wasmcc , unless we need it?
> 
> Looks like a very clean upgrade otherwise.

Thanks for pointing out @MHBauer

**Review by MHBauer — APPROVED** [review]
I'm fine with merging, but would prefer a bit more detail on the why this is necessary/desired. Are there any new features enabled or upstream bugfixes we are looking for?

I do love a good "update dependencies" type commits, and often I do them just because the dependencies exist.

If there is a specific reason to upgrade, we should write it down.

**Comment by kleash** [comment]
> I'm fine with merging, but would prefer a bit more detail on the why this is necessary/desired. Are there any new features enabled or upstream bugfixes we are looking for?
> 
> I do love a good "update dependencies" type commits, and often I do them just because the dependencies exist.
> 
> If there is a specific reason to upgrade, we should write it down.

It's majorly for updating underlying wagon. Previously we were using wagon v0.3 indirectly which is now upgraded to v0.6. It will be good to keep wagon updated as I am tracking a few of their future features which can help is improving few things.

**Pull request merged**
